# Generated by Django 4.0.3 on 2022-12-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girdi',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='girdi',
            name='sube',
        ),
        migrations.CreateModel(
            name='Icmal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now=True)),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sube')),
            ],
        ),
        migrations.AddField(
            model_name='girdi',
            name='icmal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.icmal'),
        ),
    ]
