# Generated by Django 4.0.3 on 2023-02-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0002_alter_firma_options_alter_firmaicmal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=10)),
                ('yil', models.CharField(choices=[(2023, 2023), (2022, 2022)], max_length=10)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GrupIcmal',
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='ay',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='yıl',
            field=models.IntegerField(choices=[(2023, 2023), (2022, 2022)], default=2023, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='ay',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='yıl',
            field=models.IntegerField(choices=[(2023, 2023), (2022, 2022)], default=2023, verbose_name='yıl'),
        ),
    ]
