# Generated by Django 4.0.3 on 2023-02-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_donem_delete_grupicmal_alter_firmaicmal_ay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sube',
            options={'ordering': ('isim',)},
        ),
        migrations.RemoveField(
            model_name='firmaicmal',
            name='damga',
        ),
        migrations.RemoveField(
            model_name='firmaicmal',
            name='hakemheyeti',
        ),
        migrations.RemoveField(
            model_name='firmaicmal',
            name='harcama',
        ),
        migrations.RemoveField(
            model_name='firmaicmal',
            name='idariceza',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='damga',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='hakemheyeti',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='harcama',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='idariceza',
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='yargı_dava_ceza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='icmal',
            name='yargı_dava_ceza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='donem',
            name='ay',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donem',
            name='yil',
            field=models.CharField(choices=[('2023', '2023'), ('2022', '2022')], max_length=10),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='ay',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=2, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='yıl',
            field=models.IntegerField(choices=[('2023', '2023'), ('2022', '2022')], default=2023, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='ay',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=2, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='yıl',
            field=models.IntegerField(choices=[('2023', '2023'), ('2022', '2022')], default=2023, verbose_name='yıl'),
        ),
    ]
