# Generated by Django 4.0.3 on 2022-12-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_grup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girdi',
            name='icmal',
        ),
        migrations.AddField(
            model_name='girdi',
            name='sube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.sube'),
        ),
        migrations.AddField(
            model_name='icmal',
            name='girdi',
            field=models.ManyToManyField(to='page.girdi'),
        ),
    ]
