# Generated by Django 4.0.3 on 2023-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_sube_options_remove_firmaicmal_damga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmal',
            name='altilitoplam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
