# Generated by Django 4.0.3 on 2022-12-18 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0004_remove_girdi_icmal_girdi_sube_icmal_girdi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icmal',
            name='girdi',
        ),
        migrations.AddField(
            model_name='icmal',
            name='toplam',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.CreateModel(
            name='IcmalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now=True)),
                ('kategori', models.CharField(choices=[('vergiler', 'Vergiler'), ('danismanlik', 'Danışmanlık ve Müşavirlik Ücretleri'), ('sgk', 'SGK Ödemeleri')], max_length=255)),
                ('konu', models.CharField(choices=[('kdv', 'Katma Değer Vergisi'), ('kdv2', 'Katma Değer Vergisi-2'), ('muhtasar', 'Muhtasar Vergisi'), ('ggkv', 'Gelir, Geçici, Kurumlar Vergisi'), ('damga', 'Tek Başına Alınan/ Düzeltme Damga Vergileri'), ('mtv', 'Motorlu Taşıtlar Vergisi'), ('ceza', 'Trafik Cezaları'), ('idariceza', 'Özel Usülsüzlük ve İdari Para Cezaları'), ('davagideri', 'Yargı ve Dava Giderleri'), ('hakemheyeti', 'Tüketici Hakem Heyeti Borçları'), ('geçmişborçlar', 'Geçmiş Aylarda Ödenmeyen Vergi Borçları'), ('tesvik', 'İş-Kur-Teşvik-Kosgeb-Personel Ücreti'), ('müsavirlik', 'Muhasebe ve Müşavirlik Hizmeti'), ('harcama', 'Muhasebe Ofisi Tarafından Yapılan Harcamalar'), ('gecmistesvik', 'Geçmiş Aylarda Ödenmeyen İşkur-Teşvik-Kosgeb-Personel Ücreti'), ('gecmismüsavirlik', 'Geçmiş Aylarda Ödenmeyen Muhasebe ve Müşavirlik Ücreti'), ('sgk', 'Sgk Primleri'), ('bagkur', 'Bağ-Kur Primleri')], max_length=255)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=11)),
                ('icmal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.icmal')),
                ('personel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
