# Generated by Django 4.0.3 on 2023-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_icmal_altilitoplam'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaicmal',
            name='altilitoplam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
