# Generated by Django 4.0.3 on 2023-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_firmaicmal_altilitoplam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donem',
            name='yil',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023')], max_length=10),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='yıl',
            field=models.IntegerField(choices=[('2022', '2022'), ('2023', '2023')], default=2023, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='yıl',
            field=models.IntegerField(choices=[('2022', '2022'), ('2023', '2023')], default=2023, verbose_name='yıl'),
        ),
    ]
