# Generated by Django 4.0.3 on 2022-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_icmal_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girdi',
            name='tarih',
        ),
        migrations.AddField(
            model_name='girdi',
            name='ay',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=12, verbose_name='ay'),
        ),
        migrations.AddField(
            model_name='girdi',
            name='yıl',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022)], default=2022, verbose_name='yıl'),
        ),
    ]
