# Generated by Django 4.0.3 on 2023-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_donem_yil_alter_firmaicmal_yıl_alter_icmal_yıl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donem',
            name='ay',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=2, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='donem',
            name='yil',
            field=models.IntegerField(choices=[('2023', '2023'), ('2022', '2022')], default=2023, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='yıl',
            field=models.IntegerField(choices=[('2023', '2023'), ('2022', '2022')], default=2023, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='yıl',
            field=models.IntegerField(choices=[('2023', '2023'), ('2022', '2022')], default=2023, verbose_name='yıl'),
        ),
    ]
