# Generated by Django 4.0.3 on 2022-12-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_icmal_tarih_remove_icmalitem_tarih_icmal_ay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girdi',
            name='personel',
        ),
    ]
