# Generated by Django 4.0.3 on 2022-12-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_icmal_bagkur_alter_icmal_ceza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmal',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.firma'),
        ),
        migrations.AddField(
            model_name='icmal',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.grup'),
        ),
        migrations.DeleteModel(
            name='IcmalItem',
        ),
    ]
