# Generated by Django 4.0.3 on 2022-12-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_girdi_personel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icmal',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='grup',
        ),
    ]
