# Generated by Django 4.0.3 on 2022-12-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_remove_icmal_firma_remove_icmal_grup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupIcmal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yıl', models.IntegerField(choices=[(2021, 2021), (2022, 2022)], default=2022, verbose_name='yıl')),
                ('ay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=12, verbose_name='ay')),
                ('kdv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('kdv2', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('muhtasar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('ggkv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('damga', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('mtv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('ceza', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('idariceza', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('davagideri', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('hakemheyeti', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('geçmişborçlar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('tesvik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('müsavirlik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('harcama', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('gecmistesvik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('gecmismüsavirlik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('sgk', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('bagkur', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('toplam', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.grup')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaIcmal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yıl', models.IntegerField(choices=[(2021, 2021), (2022, 2022)], default=2022, verbose_name='yıl')),
                ('ay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=12, verbose_name='ay')),
                ('kdv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('kdv2', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('muhtasar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('ggkv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('damga', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('mtv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('ceza', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('idariceza', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('davagideri', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('hakemheyeti', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('geçmişborçlar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('tesvik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('müsavirlik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('harcama', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('gecmistesvik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('gecmismüsavirlik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('sgk', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('bagkur', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('toplam', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.firma')),
            ],
        ),
    ]
