# Generated by Django 4.0.3 on 2022-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_grupicmal_firmaicmal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girdi',
            name='konu',
        ),
        migrations.RemoveField(
            model_name='girdi',
            name='tutar',
        ),
        migrations.AddField(
            model_name='girdi',
            name='bagkur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='ceza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='damga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='davagideri',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='gecmismüsavirlik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='gecmistesvik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='geçmişborçlar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='ggkv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='hakemheyeti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='harcama',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='idariceza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='kdv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='kdv2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='mtv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='muhtasar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='müsavirlik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='sgk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='tesvik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='ay',
            field=models.IntegerField(choices=[(11, 11)], default=12, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='firmaicmal',
            name='yıl',
            field=models.IntegerField(choices=[(2022, 2022)], default=2022, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='girdi',
            name='ay',
            field=models.IntegerField(choices=[(11, 11)], default=12, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='girdi',
            name='yıl',
            field=models.IntegerField(choices=[(2022, 2022)], default=2022, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='grupicmal',
            name='ay',
            field=models.IntegerField(choices=[(11, 11)], default=12, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='grupicmal',
            name='yıl',
            field=models.IntegerField(choices=[(2022, 2022)], default=2022, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='ay',
            field=models.IntegerField(choices=[(11, 11)], default=12, verbose_name='ay'),
        ),
        migrations.AlterField(
            model_name='icmal',
            name='yıl',
            field=models.IntegerField(choices=[(2022, 2022)], default=2022, verbose_name='yıl'),
        ),
    ]
