# Generated by Django 4.0.3 on 2022-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_icmal_danismanliktoplami_icmal_sgktoplamlari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaicmal',
            name='danismanliktoplami',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='sgktoplamlari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='vergilertoplami',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
