# Generated by Django 4.0.3 on 2022-12-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_firmaicmal_danismanliktoplami_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupicmal',
            name='danismanliktoplami',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='sgktoplamlari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='vergilertoplami',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
