# Generated by Django 4.0.3 on 2022-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_icmal_cezalar_icmal_digercezalar_icmal_kdvler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaicmal',
            name='cezalar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='digercezalar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='kdvler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='kosgebler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='müsavirlikler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='cezalar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='digercezalar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='kdvler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='kosgebler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='müsavirlikler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
