# Generated by Django 4.0.3 on 2023-01-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_remove_grupicmal_grup_remove_firma_grup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girdi',
            name='atak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='yasalKdv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='sube',
            name='sgkNo',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
