# Generated by Django 4.0.3 on 2023-01-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_girdi_atak_girdi_yasalkdv_sube_sgkno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmaicmal',
            name='gecmismüsavirlik',
        ),
        migrations.RemoveField(
            model_name='firmaicmal',
            name='gecmistesvik',
        ),
        migrations.RemoveField(
            model_name='girdi',
            name='gecmismüsavirlik',
        ),
        migrations.RemoveField(
            model_name='girdi',
            name='gecmistesvik',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='gecmismüsavirlik',
        ),
        migrations.RemoveField(
            model_name='icmal',
            name='gecmistesvik',
        ),
    ]
