# Generated by Django 4.0.3 on 2023-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_remove_firmaicmal_gecmismüsavirlik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaicmal',
            name='atak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='yasalKdv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='icmal',
            name='atak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='icmal',
            name='yasalKdv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
