# Generated by Django 4.0.3 on 2023-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_firmaicmal_atak_firmaicmal_yasalkdv_icmal_atak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaicmal',
            name='tasdik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='girdi',
            name='tasdik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='icmal',
            name='tasdik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
