# Generated by Django 4.0.3 on 2023-01-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0026_firmaicmal_tasdik_girdi_tasdik_icmal_tasdik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icmal',
            old_name='vergilertoplami',
            new_name='odemelertoplami',
        ),
    ]
