# Generated by Django 4.0.3 on 2023-01-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_rename_vergilertoplami_icmal_odemelertoplami'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmaicmal',
            old_name='vergilertoplami',
            new_name='odemelertoplami',
        ),
    ]
