# Generated by Django 4.0.3 on 2023-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_rename_vergilertoplami_firmaicmal_odemelertoplami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmaicmal',
            name='toplam',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=11, null=True),
        ),
    ]
