# Generated by Django 4.0.3 on 2023-01-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_alter_firmaicmal_toplam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmaicmal',
            name='toplam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
