# Generated by Django 4.0.3 on 2023-01-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_alter_firmaicmal_toplam'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmal',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.firma'),
        ),
    ]
