# Generated by Django 4.0.3 on 2023-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_icmal_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupIcmal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250)),
                ('yıl', models.IntegerField(choices=[(2022, 2022)], default=2023, verbose_name='yıl')),
                ('ay', models.IntegerField(choices=[(12, 12)], default=1, verbose_name='ay')),
                ('atak', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('yasalKdv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('tasdik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('kdv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('kdv2', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('muhtasar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('ggkv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('damga', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('mtv', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('ceza', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('idariceza', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('davagideri', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('hakemheyeti', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('geçmişborçlar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('odemelertoplami', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('kdvler', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('cezalar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('digercezalar', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('kosgebler', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('müsavirlikler', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('tesvik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('müsavirlik', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('harcama', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('danismanliktoplami', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('sgk', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('bagkur', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('sgktoplamlari', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('toplam', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sube',
            options={'ordering': ('firma__isim',)},
        ),
    ]
