# Generated by Django 4.0.3 on 2023-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0032_grupicmal_alter_sube_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sube',
            name='merkez',
            field=models.BooleanField(default=False),
        ),
    ]
