# Generated by Django 4.0.3 on 2023-01-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0033_sube_merkez'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Girdi',
        ),
    ]
