# Generated by Django 4.0.3 on 2023-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0034_delete_girdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmal',
            name='sgkYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='icmal',
            name='vergiYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='FirmaIcmal',
            name='sgkYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='FirmaIcmal',
            name='vergiYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
