# Generated by Django 4.0.3 on 2023-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0035_icmal_sgkyapilandirmasi_icmal_vergiyapilandirmasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupicmal',
            name='sgkYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='grupicmal',
            name='vergiYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
