# Generated by Django 4.0.3 on 2023-01-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0036_grupicmal_sgkyapilandirmasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmaicmal',
            name='sgkYapilandirmasi',
        ),
        migrations.RemoveField(
            model_name='firmaicmal',
            name='vergiYapilandirmasi',
        ),
    ]
