# Generated by Django 4.0.3 on 2023-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0037_remove_firmaicmal_sgkyapilandirmasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaicmal',
            name='sgkYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='firmaicmal',
            name='vergiYapilandirmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
