# Generated by Django 4.0.3 on 2023-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0040_icmal_dortlutoplam'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmal',
            name='beslitoplam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
